### ISSUE TITLE
new build\release extension does not build out of the box.

### ISSUE THREAD

**Issue by jabbera** [ALM-Rangers/generator-team-services-extension#22]
After generating a new build extension the tool attempts to package the extension into a visx. tsc is failing with the below error. Full text even further down. Thanks!

```
b/node_modules/vsts-task-lib/task.d.ts(2,21): error TS2307: Cannot find module 'fs'.
b/node_modules/vsts-task-lib/task.d.ts(8,32): error TS2503: Cannot find namespace 'NodeJS'.
b/node_modules/vsts-task-lib/task.d.ts(9,32): error TS2503: Cannot find namespace 'NodeJS'.
b/node_modules/vsts-task-lib/task.d.ts(210,64): error TS2304: Cannot find name 'Buffer'.
b/node_modules/vsts-task-lib/toolrunner.d.ts(2,25): error TS2307: Cannot find module 'events'.
b/node_modules/vsts-task-lib/toolrunner.d.ts(3,25): error TS2307: Cannot find module 'stream'.
```

```
C:\WTF>node --version
v6.11.0

C:\WTF>npm install -g yo
C:\Users\mbarry\AppData\Roaming\npm\yo -> C:\Users\mbarry\AppData\Roaming\npm\node_modules\yo\lib\cli.js
C:\Users\mbarry\AppData\Roaming\npm\yo-complete -> C:\Users\mbarry\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js

> yo@2.0.0 postinstall C:\Users\mbarry\AppData\Roaming\npm\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version

Everything looks all right!
C:\Users\mbarry\AppData\Roaming\npm
`-- yo@2.0.0


C:\WTF>npm install -g generator-team-services-extension
C:\Users\mbarry\AppData\Roaming\npm
`-- generator-team-services-extension@1.0.44


C:\WTF>yo team-services-extension

     _-----_     ╭──────────────────────────╮
    |       |    │ Welcome to Team Services │
    |--(o)--|    │        Extensions        │
   `---------´   │         v.1.0.44         │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What type of extension do you want to create? Build/Release custom Task
? Please enter the (friendly) name of your extension: b
? Please enter the ID of your extension: b
? Please enter a description of your extension: b
? Please enter the name of your marketplace publisher ID: b
? Please enter the name (Id) of your task: b
? Please enter the friendly (display) name of your task: b
? Please enter a description for your task: b
? Please select the type of task you would like to create: Build
? Please select the visibility level for your task (check all that apply): Build, Release
? Please select the scripting type for your task: TypeScript
? Do you intend to use Visual Studio ? No
   create b\static\images\logo.png
   create b\static\images\Screen1.png
   create b\b\b.ts
   create b\b\package.json
   create b\tsconfig.json
   create b\b\task.json
   create b\b\icon.png
   create b\vss-extension.json
   create b\package.json
   create b\license.md
   create b\overview.md
   create b\ThirdPartyNotices.txt
   create b\.gitignore
+ Running npm install on b
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
+ Running npm run package for vsix generating
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN task@1.0.0 No repository field.
npm WARN task@1.0.0 No license field.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mbarry\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "compile"
npm ERR! node v6.11.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! packagetask@0.0.1 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the packagetask@0.0.1 compile script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the packagetask package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs packagetask
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls packagetask
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WTF\b\npm-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mbarry\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "package"
npm ERR! node v6.11.0
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! packagetask@0.0.1 package: `npm run clean  && npm run compile  && tfx extension create  --rev-version`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the packagetask@0.0.1 package script 'npm run clean  && npm run compile  && tfx extension create  --rev-version'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the packagetask package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean  && npm run compile  && tfx extension create  --rev-version
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs packagetask
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls packagetask
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WTF\b\npm-debug.log
Done

C:\WTF>cd b

C:\WTF\b>tsc -p .
b/node_modules/vsts-task-lib/task.d.ts(2,21): error TS2307: Cannot find module 'fs'.
b/node_modules/vsts-task-lib/task.d.ts(8,32): error TS2503: Cannot find namespace 'NodeJS'.
b/node_modules/vsts-task-lib/task.d.ts(9,32): error TS2503: Cannot find namespace 'NodeJS'.
b/node_modules/vsts-task-lib/task.d.ts(210,64): error TS2304: Cannot find name 'Buffer'.
b/node_modules/vsts-task-lib/toolrunner.d.ts(2,25): error TS2307: Cannot find module 'events'.
b/node_modules/vsts-task-lib/toolrunner.d.ts(3,25): error TS2307: Cannot find module 'stream'.
```

**Comment by mikaelkrief** [comment]
I reproducted your error after upgraded my Yo version to 2.0.0.
I will investigate for fix this.

**Comment by mikaelkrief** [comment]
@jabbera is fixed in latest release (1.0.45).
Could you try ?

**Comment by jeffrey-opdam** [comment]
We have deprecated the generator, therefor we are closing this issue.
